/**
 * Env key names and app constants. Single source of truth for env var names.
 */

export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_PATH: 'DATABASE_PATH',
  BETTER_AUTH_SECRET: 'BETTER_AUTH_SECRET',
  BETTER_AUTH_URL: 'BETTER_AUTH_URL',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  AWS_SES_REGION: 'AWS_SES_REGION',
  /** Standard AWS SDK / IAM / EC2 metadata region; used as fallback when `AWS_SES_REGION` is unset. */
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  FROM_EMAIL: 'FROM_EMAIL',
  FRONTEND_URL: 'FRONTEND_URL',
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
  STRIPE_PRICE_PRO_MONTHLY: 'STRIPE_PRICE_PRO_MONTHLY',
  STRIPE_PRICE_PRO_YEARLY: 'STRIPE_PRICE_PRO_YEARLY',
  STRIPE_SUCCESS_URL: 'STRIPE_SUCCESS_URL',
  STRIPE_CANCEL_URL: 'STRIPE_CANCEL_URL',
  STRIPE_PORTAL_RETURN_URL: 'STRIPE_PORTAL_RETURN_URL',
  S3_REGION: 'S3_REGION',
  S3_BUCKET_CAPTURES: 'S3_BUCKET_CAPTURES',
  S3_ENDPOINT: 'S3_ENDPOINT',
  S3_FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  INTERNAL_API_KEY: 'INTERNAL_API_KEY',
  ANTHROPIC_API_KEY: 'ANTHROPIC_API_KEY',
  SUPPORT_EMAIL: 'SUPPORT_EMAIL',
  FEEDBACK_EMAIL: 'FEEDBACK_EMAIL',
  ADMIN_ORIGIN: 'ADMIN_ORIGIN',
  INTERNAL_TOOLS_PATH: 'INTERNAL_TOOLS_PATH',
  ADMIN_EMAILS: 'ADMIN_EMAILS',
} as const;

export const DEFAULTS = {
  PORT: 3000,
  DATABASE_PATH: './data/element-armory.db',
  /** Host port for local admin SPA (see root start.sh / docker-compose ADMIN_PORT). */
  ADMIN_ORIGIN_LOCAL: 'http://localhost:9920',
} as const;
